# Generated by Django 3.2.14 on 2022-07-22 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_jobstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpostactivity',
            name='job_post_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='post.jobstatus'),
        ),
    ]
